FROM mcr.microsoft.com/dotnet/aspnet:8.0
ENV TZ=Asia/Shanghai

ENV UMASK=022
ENV PUID=0
ENV PGID=0

WORKDIR /app
VOLUME [ "/rec" ]

COPY --from=tianon/gosu:1.17 /gosu /usr/local/bin/
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
COPY ./BililiveRecorder.Cli/bin/docker_out /app

RUN chmod a+x /usr/local/bin/docker-entrypoint.sh && \
    chmod -R 777 /app && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

EXPOSE 2356/tcp

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD [ "run", "--bind", "http://*:2356", "/rec" ]
