FROM mcr.microsoft.com/dotnet/aspnet:6.0
ENV TZ=Asia/Shanghai

ENV UMASK=022
ENV PUID=1000
ENV PGID=1000


WORKDIR /app
VOLUME [ "/rec" ]

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
COPY ./BililiveRecorder.Cli/bin/docker_out /app

ARG TARGETPLATFORM
RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then GOSU_FILE=gosu-amd64; fi; if [ "$TARGETPLATFORM" = "linux/arm64" ]; then GOSU_FILE=gosu-arm64; fi; if [ "$TARGETPLATFORM" = "linux/arm/v7" ]; then GOSU_FILE=gosu-armhf; fi

RUN apt-get update && \
    apt-get install -y wget && \
    wget -O /usr/local/bin/gosu https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/$GOSU_FILE && \
    chmod +x /usr/local/bin/gosu && \
    useradd -r -g users user && \
    chmod a+x /usr/local/bin/docker-entrypoint.sh && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

EXPOSE 2356/tcp

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD [ "run", "--bind", "http://*:2356", "/rec" ]
