//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BililiveRecorder.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BililiveRecorder.WPF.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公告获取失败.
        /// </summary>
        public static string AnnouncementPage_FetchFailed {
            get {
                return ResourceManager.GetString("AnnouncementPage_FetchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新公告内容.
        /// </summary>
        public static string AnnouncementPage_RefreshButton {
            get {
                return ResourceManager.GetString("AnnouncementPage_RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Global_Cancel {
            get {
                return ResourceManager.GetString("Global_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string Global_Confirm {
            get {
                return ResourceManager.GetString("Global_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        public static string Global_Copy {
            get {
                return ResourceManager.GetString("Global_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string Global_Quit {
            get {
                return ResourceManager.GetString("Global_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右键点击可以复制单行日志.
        /// </summary>
        public static string LogPage_RightClickCopyToolTip {
            get {
                return ResourceManager.GetString("LogPage_RightClickCopyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除房间.
        /// </summary>
        public static string RoomCard_Menu_Delete {
            get {
                return ResourceManager.GetString("RoomCard_Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不自动录制.
        /// </summary>
        public static string RoomCard_Menu_DisableAutoRecord {
            get {
                return ResourceManager.GetString("RoomCard_Menu_DisableAutoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动录制.
        /// </summary>
        public static string RoomCard_Menu_EnableAutoRecord {
            get {
                return ResourceManager.GetString("RoomCard_Menu_EnableAutoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开直播间页面.
        /// </summary>
        public static string RoomCard_Menu_OpenInBrowser {
            get {
                return ResourceManager.GetString("RoomCard_Menu_OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新直播间信息.
        /// </summary>
        public static string RoomCard_Menu_RefreshInfo {
            get {
                return ResourceManager.GetString("RoomCard_Menu_RefreshInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始录制.
        /// </summary>
        public static string RoomCard_Menu_StartRecording {
            get {
                return ResourceManager.GetString("RoomCard_Menu_StartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止录制.
        /// </summary>
        public static string RoomCard_Menu_StopRecording {
            get {
                return ResourceManager.GetString("RoomCard_Menu_StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        public static string RoomCard_Menu_Tooltip {
            get {
                return ResourceManager.GetString("RoomCard_Menu_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 监控.
        /// </summary>
        public static string RoomListPage_Menu_AutoRecord {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_AutoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消自动录制全部房间.
        /// </summary>
        public static string RoomListPage_Menu_AutoRecord_DisableAll {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_AutoRecord_DisableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动录制全部房间.
        /// </summary>
        public static string RoomListPage_Menu_AutoRecord_EnableAll {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_AutoRecord_EnableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件.
        /// </summary>
        public static string RoomListPage_Menu_File {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开工作目录.
        /// </summary>
        public static string RoomListPage_Menu_File_OpenWorkDirectory {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_File_OpenWorkDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志.
        /// </summary>
        public static string RoomListPage_Menu_Log {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不在本页显示日志.
        /// </summary>
        public static string RoomListPage_Menu_Log_Hide {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Log_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在本页显示日志.
        /// </summary>
        public static string RoomListPage_Menu_Log_Show {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Log_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排序.
        /// </summary>
        public static string RoomListPage_Menu_Sort {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不排序.
        /// </summary>
        public static string RoomListPage_Menu_Sort_Default {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Sort_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间号.
        /// </summary>
        public static string RoomListPage_Menu_Sort_RoomId {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Sort_RoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 录制状态.
        /// </summary>
        public static string RoomListPage_Menu_Sort_Status {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Sort_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高级设置.
        /// </summary>
        public static string RootPage_NavigationViewItem_AdvancedSettingsPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_AdvancedSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公告.
        /// </summary>
        public static string RootPage_NavigationViewItem_AnnouncementPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_AnnouncementPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志.
        /// </summary>
        public static string RootPage_NavigationViewItem_LogPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_LogPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间列表.
        /// </summary>
        public static string RootPage_NavigationViewItem_RoomListPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_RoomListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string RootPage_NavigationViewItem_SettingsPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_SettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B站录播姬 {0}.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览....
        /// </summary>
        public static string WorkDirectorySelector_Browse {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择工作目录.
        /// </summary>
        public static string WorkDirectorySelector_Title {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Title", resourceCulture);
            }
        }
    }
}
