//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BililiveRecorder.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BililiveRecorder.WPF.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string AddRoomCard_ConfirmButton {
            get {
                return ResourceManager.GetString("AddRoomCard_ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间号或房间链接.
        /// </summary>
        public static string AddRoomCard_PlaceholderText {
            get {
                return ResourceManager.GetString("AddRoomCard_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加房间.
        /// </summary>
        public static string AddRoomCard_Title {
            get {
                return ResourceManager.GetString("AddRoomCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 知道了.
        /// </summary>
        public static string AddRoomFailedDialog_CloseButtonText {
            get {
                return ResourceManager.GetString("AddRoomFailedDialog_CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这个直播间已经被添加过了.
        /// </summary>
        public static string AddRoomFailedDialog_ErrorText_Duplicate {
            get {
                return ResourceManager.GetString("AddRoomFailedDialog_ErrorText_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入B站直播房间号或直播间链接.
        /// </summary>
        public static string AddRoomFailedDialog_ErrorText_InvalidInput {
            get {
                return ResourceManager.GetString("AddRoomFailedDialog_ErrorText_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间号不能是负数.
        /// </summary>
        public static string AddRoomFailedDialog_ErrorText_RoomIdNegative {
            get {
                return ResourceManager.GetString("AddRoomFailedDialog_ErrorText_RoomIdNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间号不能是 0.
        /// </summary>
        public static string AddRoomFailedDialog_ErrorText_RoomIdZero {
            get {
                return ResourceManager.GetString("AddRoomFailedDialog_ErrorText_RoomIdZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加房间失败.
        /// </summary>
        public static string AddRoomFailedDialog_Title {
            get {
                return ResourceManager.GetString("AddRoomFailedDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公告获取失败.
        /// </summary>
        public static string AnnouncementPage_FetchFailed {
            get {
                return ResourceManager.GetString("AnnouncementPage_FetchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新公告内容.
        /// </summary>
        public static string AnnouncementPage_RefreshButton {
            get {
                return ResourceManager.GetString("AnnouncementPage_RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要退出吗？.
        /// </summary>
        public static string CloseWindowConfirmDialog_Title {
            get {
                return ResourceManager.GetString("CloseWindowConfirmDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要删除这个直播间吗？.
        /// </summary>
        public static string DeleteRoomConfirmDialog_Title {
            get {
                return ResourceManager.GetString("DeleteRoomConfirmDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Global_Cancel {
            get {
                return ResourceManager.GetString("Global_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string Global_Confirm {
            get {
                return ResourceManager.GetString("Global_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        public static string Global_Copy {
            get {
                return ResourceManager.GetString("Global_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Global_Delete {
            get {
                return ResourceManager.GetString("Global_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string Global_Quit {
            get {
                return ResourceManager.GetString("Global_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右键点击可以复制单行日志.
        /// </summary>
        public static string LogPage_RightClickCopyToolTip {
            get {
                return ResourceManager.GetString("LogPage_RightClickCopyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回放剪辑（正在处理中的数量）.
        /// </summary>
        public static string RoomCard_ClipButton_Tooltip {
            get {
                return ResourceManager.GetString("RoomCard_ClipButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除房间.
        /// </summary>
        public static string RoomCard_Menu_Delete {
            get {
                return ResourceManager.GetString("RoomCard_Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不自动录制.
        /// </summary>
        public static string RoomCard_Menu_DisableAutoRecord {
            get {
                return ResourceManager.GetString("RoomCard_Menu_DisableAutoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动录制.
        /// </summary>
        public static string RoomCard_Menu_EnableAutoRecord {
            get {
                return ResourceManager.GetString("RoomCard_Menu_EnableAutoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开直播间页面.
        /// </summary>
        public static string RoomCard_Menu_OpenInBrowser {
            get {
                return ResourceManager.GetString("RoomCard_Menu_OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新直播间信息.
        /// </summary>
        public static string RoomCard_Menu_RefreshInfo {
            get {
                return ResourceManager.GetString("RoomCard_Menu_RefreshInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始录制.
        /// </summary>
        public static string RoomCard_Menu_StartRecording {
            get {
                return ResourceManager.GetString("RoomCard_Menu_StartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止录制.
        /// </summary>
        public static string RoomCard_Menu_StopRecording {
            get {
                return ResourceManager.GetString("RoomCard_Menu_StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        public static string RoomCard_Menu_Tooltip {
            get {
                return ResourceManager.GetString("RoomCard_Menu_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 监控中.
        /// </summary>
        public static string RoomCard_Status_Monitoring {
            get {
                return ResourceManager.GetString("RoomCard_Status_Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 录制中.
        /// </summary>
        public static string RoomCard_Status_Recording {
            get {
                return ResourceManager.GetString("RoomCard_Status_Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这里显示的是录制的速度与主播直播速度的比
        ///正常应为接近 100% 颜色显示为绿色.
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_Description {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F2} Mbps.
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_SpeedInMbps {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_SpeedInMbps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前速度比： {0:P2}.
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_SpeedInPercentage {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_SpeedInPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 监控.
        /// </summary>
        public static string RoomListPage_Menu_AutoRecord {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_AutoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消自动录制全部房间.
        /// </summary>
        public static string RoomListPage_Menu_AutoRecord_DisableAll {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_AutoRecord_DisableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动录制全部房间.
        /// </summary>
        public static string RoomListPage_Menu_AutoRecord_EnableAll {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_AutoRecord_EnableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件.
        /// </summary>
        public static string RoomListPage_Menu_File {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开工作目录.
        /// </summary>
        public static string RoomListPage_Menu_File_OpenWorkDirectory {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_File_OpenWorkDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志.
        /// </summary>
        public static string RoomListPage_Menu_Log {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不在本页显示日志.
        /// </summary>
        public static string RoomListPage_Menu_Log_Hide {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Log_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在本页显示日志.
        /// </summary>
        public static string RoomListPage_Menu_Log_Show {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Log_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排序.
        /// </summary>
        public static string RoomListPage_Menu_Sort {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不排序.
        /// </summary>
        public static string RoomListPage_Menu_Sort_Default {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Sort_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间号.
        /// </summary>
        public static string RoomListPage_Menu_Sort_RoomId {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Sort_RoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 录制状态.
        /// </summary>
        public static string RoomListPage_Menu_Sort_Status {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Sort_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高级设置.
        /// </summary>
        public static string RootPage_NavigationViewItem_AdvancedSettingsPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_AdvancedSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公告.
        /// </summary>
        public static string RootPage_NavigationViewItem_AnnouncementPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_AnnouncementPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志.
        /// </summary>
        public static string RootPage_NavigationViewItem_LogPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_LogPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间列表.
        /// </summary>
        public static string RootPage_NavigationViewItem_RoomListPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_RoomListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string RootPage_NavigationViewItem_SettingsPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_SettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开主界面.
        /// </summary>
        public static string TaskbarIconControl_MenuItem_OpenMainWindow {
            get {
                return ResourceManager.GetString("TaskbarIconControl_MenuItem_OpenMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 录播姬已最小化到托盘，左键单击图标恢复界面.
        /// </summary>
        public static string TaskbarIconControl_MinimizedNotification {
            get {
                return ResourceManager.GetString("TaskbarIconControl_MinimizedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B站录播姬.
        /// </summary>
        public static string TaskbarIconControl_Title {
            get {
                return ResourceManager.GetString("TaskbarIconControl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B站录播姬 {0}.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览....
        /// </summary>
        public static string WorkDirectorySelector_Browse {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择工作目录.
        /// </summary>
        public static string WorkDirectorySelector_Title {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Title", resourceCulture);
            }
        }
    }
}
