//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BililiveRecorder.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BililiveRecorder.WPF.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联系方式.
        /// </summary>
        public static string About_Contact {
            get {
                return ResourceManager.GetString("About_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版权所有.
        /// </summary>
        public static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用的库.
        /// </summary>
        public static string About_LibrariesUsed {
            get {
                return ResourceManager.GetString("About_LibrariesUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本软件为免费软件。
        ///本软件为开源软件，使用 GNU通用公共许可证第三版 （GPLv3） 授权。.
        /// </summary>
        public static string About_License {
            get {
                return ResourceManager.GetString("About_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B站录播姬.
        /// </summary>
        public static string About_Name {
            get {
                return ResourceManager.GetString("About_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目首页.
        /// </summary>
        public static string About_Project {
            get {
                return ResourceManager.GetString("About_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 翻译者.
        /// </summary>
        public static string About_Translator {
            get {
                return ResourceManager.GetString("About_Translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本 {0}.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 官方网站.
        /// </summary>
        public static string About_Website {
            get {
                return ResourceManager.GetString("About_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string AddRoomCard_ConfirmButton {
            get {
                return ResourceManager.GetString("AddRoomCard_ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间号或房间链接.
        /// </summary>
        public static string AddRoomCard_PlaceholderText {
            get {
                return ResourceManager.GetString("AddRoomCard_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        public static string AddRoomCard_PlaceholderText_FontSize {
            get {
                return ResourceManager.GetString("AddRoomCard_PlaceholderText_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加房间.
        /// </summary>
        public static string AddRoomCard_Title {
            get {
                return ResourceManager.GetString("AddRoomCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 知道了.
        /// </summary>
        public static string AddRoomFailedDialog_CloseButtonText {
            get {
                return ResourceManager.GetString("AddRoomFailedDialog_CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这个直播间已经被添加过了.
        /// </summary>
        public static string AddRoomFailedDialog_ErrorText_Duplicate {
            get {
                return ResourceManager.GetString("AddRoomFailedDialog_ErrorText_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入B站直播房间号或直播间链接.
        /// </summary>
        public static string AddRoomFailedDialog_ErrorText_InvalidInput {
            get {
                return ResourceManager.GetString("AddRoomFailedDialog_ErrorText_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间号不能是负数.
        /// </summary>
        public static string AddRoomFailedDialog_ErrorText_RoomIdNegative {
            get {
                return ResourceManager.GetString("AddRoomFailedDialog_ErrorText_RoomIdNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间号不能是 0.
        /// </summary>
        public static string AddRoomFailedDialog_ErrorText_RoomIdZero {
            get {
                return ResourceManager.GetString("AddRoomFailedDialog_ErrorText_RoomIdZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加房间失败.
        /// </summary>
        public static string AddRoomFailedDialog_Title {
            get {
                return ResourceManager.GetString("AddRoomFailedDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公告获取失败.
        /// </summary>
        public static string AnnouncementPage_FetchFailed {
            get {
                return ResourceManager.GetString("AnnouncementPage_FetchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新公告内容.
        /// </summary>
        public static string AnnouncementPage_RefreshButton {
            get {
                return ResourceManager.GetString("AnnouncementPage_RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要退出吗？.
        /// </summary>
        public static string CloseWindowConfirmDialog_Title {
            get {
                return ResourceManager.GetString("CloseWindowConfirmDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要删除这个直播间吗？.
        /// </summary>
        public static string DeleteRoomConfirmDialog_Title {
            get {
                return ResourceManager.GetString("DeleteRoomConfirmDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Global_Cancel {
            get {
                return ResourceManager.GetString("Global_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string Global_Close {
            get {
                return ResourceManager.GetString("Global_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string Global_Confirm {
            get {
                return ResourceManager.GetString("Global_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        public static string Global_Copy {
            get {
                return ResourceManager.GetString("Global_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Global_Delete {
            get {
                return ResourceManager.GetString("Global_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string Global_Quit {
            get {
                return ResourceManager.GetString("Global_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右键点击可以复制单行日志.
        /// </summary>
        public static string LogPage_RightClickCopyToolTip {
            get {
                return ResourceManager.GetString("LogPage_RightClickCopyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回放剪辑（正在处理中的数量）.
        /// </summary>
        public static string RoomCard_ClipButton_Tooltip {
            get {
                return ResourceManager.GetString("RoomCard_ClipButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除房间.
        /// </summary>
        public static string RoomCard_Menu_Delete {
            get {
                return ResourceManager.GetString("RoomCard_Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不自动录制.
        /// </summary>
        public static string RoomCard_Menu_DisableAutoRecord {
            get {
                return ResourceManager.GetString("RoomCard_Menu_DisableAutoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动录制.
        /// </summary>
        public static string RoomCard_Menu_EnableAutoRecord {
            get {
                return ResourceManager.GetString("RoomCard_Menu_EnableAutoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开直播间页面.
        /// </summary>
        public static string RoomCard_Menu_OpenInBrowser {
            get {
                return ResourceManager.GetString("RoomCard_Menu_OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新直播间信息.
        /// </summary>
        public static string RoomCard_Menu_RefreshInfo {
            get {
                return ResourceManager.GetString("RoomCard_Menu_RefreshInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间设置.
        /// </summary>
        public static string RoomCard_Menu_Settings {
            get {
                return ResourceManager.GetString("RoomCard_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始录制.
        /// </summary>
        public static string RoomCard_Menu_StartRecording {
            get {
                return ResourceManager.GetString("RoomCard_Menu_StartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止录制.
        /// </summary>
        public static string RoomCard_Menu_StopRecording {
            get {
                return ResourceManager.GetString("RoomCard_Menu_StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        public static string RoomCard_Menu_Tooltip {
            get {
                return ResourceManager.GetString("RoomCard_Menu_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切割录制输出文件.
        /// </summary>
        public static string RoomCard_SplitButton_Tooltip {
            get {
                return ResourceManager.GetString("RoomCard_SplitButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本次直播不再自动录制，结束直播时恢复.
        /// </summary>
        public static string RoomCard_Status_AutoRecordForThisSessionDisabled_Tooltip {
            get {
                return ResourceManager.GetString("RoomCard_Status_AutoRecordForThisSessionDisabled_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弹幕连接被断开
        ///录播姬通过弹幕服务器接收开播状态推送.
        /// </summary>
        public static string RoomCard_Status_DanmakuConnectionTooltip_False {
            get {
                return ResourceManager.GetString("RoomCard_Status_DanmakuConnectionTooltip_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已连接弹幕服务器
        ///实时接收开播状态和其他数据.
        /// </summary>
        public static string RoomCard_Status_DanmakuConnectionTooltip_True {
            get {
                return ResourceManager.GetString("RoomCard_Status_DanmakuConnectionTooltip_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未开播.
        /// </summary>
        public static string RoomCard_Status_LiveStatusTooltip_False {
            get {
                return ResourceManager.GetString("RoomCard_Status_LiveStatusTooltip_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 直播中.
        /// </summary>
        public static string RoomCard_Status_LiveStatusTooltip_True {
            get {
                return ResourceManager.GetString("RoomCard_Status_LiveStatusTooltip_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 监控中.
        /// </summary>
        public static string RoomCard_Status_Monitoring {
            get {
                return ResourceManager.GetString("RoomCard_Status_Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 录制中.
        /// </summary>
        public static string RoomCard_Status_Recording {
            get {
                return ResourceManager.GetString("RoomCard_Status_Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前文件时长: {0:g}.
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_CurrentFileDuration {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_CurrentFileDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这里显示的是录制的速度与主播直播速度的比
        ///正常应为接近 100% 颜色显示为绿色.
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_Description {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无统计数据.
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_NoData {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 录制经过时间: {0:g}.
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_SessionDuration {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_SessionDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F2} Mbps.
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_SpeedInMbps {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_SpeedInMbps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前速度比： {0:P2}.
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_SpeedInPercentage {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_SpeedInPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有文件时长: {0:g}.
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_TotalFileDuration {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_TotalFileDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接收数据量 {0}.
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_TotalnputBytes {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_TotalnputBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 写入数据量 {0}.
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_TotalOutputBytes {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_TotalOutputBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 监控.
        /// </summary>
        public static string RoomListPage_Menu_AutoRecord {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_AutoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消自动录制全部房间.
        /// </summary>
        public static string RoomListPage_Menu_AutoRecord_DisableAll {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_AutoRecord_DisableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动录制全部房间.
        /// </summary>
        public static string RoomListPage_Menu_AutoRecord_EnableAll {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_AutoRecord_EnableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件.
        /// </summary>
        public static string RoomListPage_Menu_File {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改工作目录（会重启）.
        /// </summary>
        public static string RoomListPage_Menu_File_ChangeWorkPath {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_File_ChangeWorkPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开工作目录.
        /// </summary>
        public static string RoomListPage_Menu_File_OpenWorkDirectory {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_File_OpenWorkDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存设置.
        /// </summary>
        public static string RoomListPage_Menu_File_SaveConfig {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_File_SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不排序.
        /// </summary>
        public static string RoomListPage_Menu_Sort_Default {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Sort_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按房间号排序.
        /// </summary>
        public static string RoomListPage_Menu_Sort_RoomId {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Sort_RoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按录制状态排序.
        /// </summary>
        public static string RoomListPage_Menu_Sort_Status {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Sort_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 视图.
        /// </summary>
        public static string RoomListPage_Menu_View {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示日志.
        /// </summary>
        public static string RoomListPage_Menu_View_ShowLogCheckBox {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_View_ShowLogCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示直播间标题和分区.
        /// </summary>
        public static string RoomListPage_Menu_View_ShowTitleAndAreaCheckBox {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_View_ShowTitleAndAreaCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高级设置.
        /// </summary>
        public static string RootPage_NavigationViewItem_AdvancedSettingsPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_AdvancedSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公告.
        /// </summary>
        public static string RootPage_NavigationViewItem_AnnouncementPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_AnnouncementPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志.
        /// </summary>
        public static string RootPage_NavigationViewItem_LogPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_LogPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 房间列表.
        /// </summary>
        public static string RootPage_NavigationViewItem_RoomListPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_RoomListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string RootPage_NavigationViewItem_SettingsPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_SettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高级设置.
        /// </summary>
        public static string Settings_AdvancedPage_Title {
            get {
                return ResourceManager.GetString("Settings_AdvancedPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注：一般用户通常不需要也不应该修改这里的设置项。
        ///对 Timing 的修改可能会导致被B站服务器屏蔽、不能及时开始录制等问题。.
        /// </summary>
        public static string Settings_AdvancedPage_Warning {
            get {
                return ResourceManager.GetString("Settings_AdvancedPage_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 触发写硬盘所需弹幕个数.
        /// </summary>
        public static string Settings_Danmaku_FlushInterval {
            get {
                return ResourceManager.GetString("Settings_Danmaku_FlushInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弹幕录制.
        /// </summary>
        public static string Settings_Danmaku_Title {
            get {
                return ResourceManager.GetString("Settings_Danmaku_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存弹幕.
        /// </summary>
        public static string Settings_Danmaku_ToggleSwitch_Enabled {
            get {
                return ResourceManager.GetString("Settings_Danmaku_ToggleSwitch_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存 送礼信息.
        /// </summary>
        public static string Settings_Danmaku_ToggleSwitch_Gift {
            get {
                return ResourceManager.GetString("Settings_Danmaku_ToggleSwitch_Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存 舰长购买.
        /// </summary>
        public static string Settings_Danmaku_ToggleSwitch_Guard {
            get {
                return ResourceManager.GetString("Settings_Danmaku_ToggleSwitch_Guard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存 弹幕原始数据.
        /// </summary>
        public static string Settings_Danmaku_ToggleSwitch_Raw {
            get {
                return ResourceManager.GetString("Settings_Danmaku_ToggleSwitch_Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存 SuperChat.
        /// </summary>
        public static string Settings_Danmaku_ToggleSwitch_SuperChat {
            get {
                return ResourceManager.GetString("Settings_Danmaku_ToggleSwitch_SuperChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剪辑文件名格式.
        /// </summary>
        public static string Settings_FileName_Clip {
            get {
                return ResourceManager.GetString("Settings_FileName_Clip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 说明.
        /// </summary>
        public static string Settings_FileName_Description_Text {
            get {
                return ResourceManager.GetString("Settings_FileName_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件名变量说明
        ///
        ///日期: {date}
        ///时间: {time}
        ///房间号: {roomid}
        ///标题: {title}
        ///主播名: {name}
        ///大分区: {parea}
        ///子分区: {area}
        ///随机数字: {random}
        ///
        ///所有大括号均为英文半角括号
        ///只支持 FLV 格式.
        /// </summary>
        public static string Settings_FileName_Description_ToolTip {
            get {
                return ResourceManager.GetString("Settings_FileName_Description_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 录制文件名格式.
        /// </summary>
        public static string Settings_FileName_Record {
            get {
                return ResourceManager.GetString("Settings_FileName_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件名.
        /// </summary>
        public static string Settings_FileName_Title {
            get {
                return ResourceManager.GetString("Settings_FileName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剪辑将来时长.
        /// </summary>
        public static string Settings_RecordMode_Clip_FutureDuration_Left {
            get {
                return ResourceManager.GetString("Settings_RecordMode_Clip_FutureDuration_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒.
        /// </summary>
        public static string Settings_RecordMode_Clip_FutureDuration_Right {
            get {
                return ResourceManager.GetString("Settings_RecordMode_Clip_FutureDuration_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剪辑过去时长.
        /// </summary>
        public static string Settings_RecordMode_Clip_PastDuration_Left {
            get {
                return ResourceManager.GetString("Settings_RecordMode_Clip_PastDuration_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒.
        /// </summary>
        public static string Settings_RecordMode_Clip_PastDuration_Right {
            get {
                return ResourceManager.GetString("Settings_RecordMode_Clip_PastDuration_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原始数据模式.
        /// </summary>
        public static string Settings_RecordMode_RadioButton_RawData {
            get {
                return ResourceManager.GetString("Settings_RecordMode_RadioButton_RawData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标准模式.
        /// </summary>
        public static string Settings_RecordMode_RadioButton_Standard {
            get {
                return ResourceManager.GetString("Settings_RecordMode_RadioButton_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 录制模式.
        /// </summary>
        public static string Settings_RecordMode_Title {
            get {
                return ResourceManager.GetString("Settings_RecordMode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Settings_SettingsPage_Title {
            get {
                return ResourceManager.GetString("Settings_SettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 根据文件大小自动分段.
        /// </summary>
        public static string Settings_Splitting_RadioButton_BySize {
            get {
                return ResourceManager.GetString("Settings_Splitting_RadioButton_BySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 根据视频时间自动分段.
        /// </summary>
        public static string Settings_Splitting_RadioButton_ByTime {
            get {
                return ResourceManager.GetString("Settings_Splitting_RadioButton_ByTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不自动分段.
        /// </summary>
        public static string Settings_Splitting_RadioButton_Disabled {
            get {
                return ResourceManager.GetString("Settings_Splitting_RadioButton_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每.
        /// </summary>
        public static string Settings_Splitting_TextBox_Left {
            get {
                return ResourceManager.GetString("Settings_Splitting_TextBox_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存为一个文件.
        /// </summary>
        public static string Settings_Splitting_TextBox_Right {
            get {
                return ResourceManager.GetString("Settings_Splitting_TextBox_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiB.
        /// </summary>
        public static string Settings_Splitting_TextBox_SizeUnit {
            get {
                return ResourceManager.GetString("Settings_Splitting_TextBox_SizeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分.
        /// </summary>
        public static string Settings_Splitting_TextBox_TimeUnit {
            get {
                return ResourceManager.GetString("Settings_Splitting_TextBox_TimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动分段.
        /// </summary>
        public static string Settings_Splitting_Title {
            get {
                return ResourceManager.GetString("Settings_Splitting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhook 地址，一行一个.
        /// </summary>
        public static string Settings_Webhook_Address {
            get {
                return ResourceManager.GetString("Settings_Webhook_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhook.
        /// </summary>
        public static string Settings_Webhook_Title {
            get {
                return ResourceManager.GetString("Settings_Webhook_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认.
        /// </summary>
        public static string SettingWithDefault_Default {
            get {
                return ResourceManager.GetString("SettingWithDefault_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开主界面.
        /// </summary>
        public static string TaskbarIconControl_MenuItem_OpenMainWindow {
            get {
                return ResourceManager.GetString("TaskbarIconControl_MenuItem_OpenMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 录播姬已最小化到托盘，左键单击图标恢复界面.
        /// </summary>
        public static string TaskbarIconControl_MinimizedNotification {
            get {
                return ResourceManager.GetString("TaskbarIconControl_MinimizedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B站录播姬.
        /// </summary>
        public static string TaskbarIconControl_Title {
            get {
                return ResourceManager.GetString("TaskbarIconControl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件内存在录播姬无法自动修复的问题
        ///请点击 修复失败？ 按钮并反馈本问题.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_ContainsUnrepairable {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_ContainsUnrepairable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要修复.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_FixNeeded {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_FixNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无需修复.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_FixNotNeeded {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_FixNotNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分辨率、解码问题 {0} 处.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_IssueTypeDecodingHeader {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_IssueTypeDecodingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他问题 {0} 处.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_IssueTypeOther {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_IssueTypeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重复片段 {0} 处.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_IssueTypeRepeatingData {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_IssueTypeRepeatingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间戳跳变问题 {0} 处.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_IssueTypeTimestampJump {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_IssueTypeTimestampJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间戳错位问题 {0} 处.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_IssueTypeTimestampOffset {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_IssueTypeTimestampOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法修复的问题 {0} 处.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_IssueTypeUnrepairable {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_IssueTypeUnrepairable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注：不分析也可以进行修复操作.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_NoDataNote {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_NoDataNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击分析按钮开始分析.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_NoDataTitle {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_NoDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修复将会输出 {0} 个文件.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_OutputFileCount {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_OutputFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音频.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_Stats_Audio {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_Stats_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均FPS {0:F2}.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_Stats_AvgFPS {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_Stats_AvgFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅供参考，有问题的文件的统计可能不准确.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_Stats_Disclaimer {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_Stats_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帧数量.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_Stats_FrameCount {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_Stats_FrameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帧数量 {0} 个.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_Stats_FrameCountTemplate {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_Stats_FrameCountTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帧时长.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_Stats_FrameDuration {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_Stats_FrameDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 统计数据.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_Stats_Title {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_Stats_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 视频.
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_Stats_Video {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_Stats_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分析.
        /// </summary>
        public static string Toolbox_AutoFix_ButtonAnalyze {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_ButtonAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修复.
        /// </summary>
        public static string Toolbox_AutoFix_ButtonFix {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_ButtonFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修复失败？.
        /// </summary>
        public static string Toolbox_AutoFix_ButtonNotFixed {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_ButtonNotFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择....
        /// </summary>
        public static string Toolbox_AutoFix_ButtonSelectInput {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_ButtonSelectInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发生了错误.
        /// </summary>
        public static string Toolbox_AutoFix_Error_Title {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知错误.
        /// </summary>
        public static string Toolbox_AutoFix_Error_Type_Error {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_Error_Type_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取文件失败.
        /// </summary>
        public static string Toolbox_AutoFix_Error_Type_InputIOError {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_Error_Type_InputIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入不是FLV文件.
        /// </summary>
        public static string Toolbox_AutoFix_Error_Type_NotFlvFile {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_Error_Type_NotFlvFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Toolbox_AutoFix_Error_Type_OK {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_Error_Type_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 写入文件失败.
        /// </summary>
        public static string Toolbox_AutoFix_Error_Type_OutputIOError {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_Error_Type_OutputIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知的FLV数据类型.
        /// </summary>
        public static string Toolbox_AutoFix_Error_Type_UnknownFlvTagType {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_Error_Type_UnknownFlvTagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLV 文件.
        /// </summary>
        public static string Toolbox_AutoFix_InputPathPlaceholder {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_InputPathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出原始分析数据.
        /// </summary>
        public static string Toolbox_AutoFix_NotFixed_ButtonExportData {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_NotFixed_ButtonExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果修复出错、或在修复后依旧有问题
        ///请发邮件到 rec@danmuji.org 反馈。
        ///在邮件内附上此处导出的分析数据，
        ///并尽量详细描述视频的问题、所使用的录播姬版本。
        ///请分析未经修复的原始文件，而不是录播姬修复后的文件.
        /// </summary>
        public static string Toolbox_AutoFix_NotFixed_Description {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_NotFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更多信息请点击这里.
        /// </summary>
        public static string Toolbox_AutoFix_NotFixed_LearnMore {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_NotFixed_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择视频文件.
        /// </summary>
        public static string Toolbox_AutoFix_SelectInputDialog_Title {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_SelectInputDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择保存位置.
        /// </summary>
        public static string Toolbox_AutoFix_SelectOutputDialog_Title {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_SelectOutputDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 录播修复.
        /// </summary>
        public static string Toolbox_AutoFix_Title {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具箱.
        /// </summary>
        public static string Toolbox_Title {
            get {
                return ResourceManager.GetString("Toolbox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B站录播姬 {0}.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览....
        /// </summary>
        public static string WorkDirectorySelector_Browse {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置文件加载失败.
        /// </summary>
        public static string WorkDirectorySelector_Error_FailedToLoadConfig {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Error_FailedToLoadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string WorkDirectorySelector_Error_None {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Error_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目录已有其他文件.
        /// </summary>
        public static string WorkDirectorySelector_Error_PathContainsFiles {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Error_PathContainsFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目录不存在.
        /// </summary>
        public static string WorkDirectorySelector_Error_PathDoesNotExist {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Error_PathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持该路径.
        /// </summary>
        public static string WorkDirectorySelector_Error_PathNotSupported {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Error_PathNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发生了未知错误.
        /// </summary>
        public static string WorkDirectorySelector_Error_UnknownError {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Error_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不再询问.
        /// </summary>
        public static string WorkDirectorySelector_SkipAsking {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_SkipAsking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择工作目录.
        /// </summary>
        public static string WorkDirectorySelector_Title {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Title", resourceCulture);
            }
        }
    }
}
