name: Update copyright years

on:
  workflow_dispatch:
  schedule:
    - cron: '12 0 1 1 *' # Run on the first day of every year at 00:12 UTC, or 08:12 UTC+8

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@f180e962fa988db222d8f03ef4636750312d1b3d # v3.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: |
            Directory.Build.props
            BililiveRecorder.WPF/Properties/AssemblyInfo.cs
          transform: '(?<=Copyright © )(?<from>\d{4})-(\d{4})'
